@startuml
skinparam linetype polyline
'skinparam linetype ortho

skinparam defaultFontName "Fira Code Retina"

package "Log Processor" {
interface accept_data
interface send_data
[Steps Register] as sr
[Field Splitter] as fs
[Serverity Normalizer] as sn
[Text Splitter] as ts
[Word Filter] as wf
[Log Accumulator] as la

accept_data -> sr : data = type + log
sr -> fs : log
fs --> sn : fields
fs -down-> ts : fields
sn -> ts : fields (severity changed)
ts -> wf : fields + word listt
wf -> la : fields + filtered word list
la -> send_data

'fs . sr
'sn . sr
'ts . sr
'wf . sr


note top of sr
  Checks data "type"
  and configure steps
  in the pipeline
end note


}


@enduml