@startuml
title Pipeline
'skinparam linetype polyline
'skinparam linetype ortho

skinparam defaultFontName "Fira Code Retina"

database IncidentDB {
}

package "Log Processor" {
interface accept_data
interface send_data
interface send_error
[Steps Register] as sr
[Field Splitter] as fs
[Serverity Normalizer] as sn
[Text Splitter] as ts
[Word Filter] as wf
[Log Accumulator] as la
[Error Handler] as eh

accept_data --> sr
sr --> fs
fs --> sn
fs --> ts
sn -> ts
ts -> wf
wf -> la
la -> send_data

sr ..> eh : error
fs ..> eh : error
sn ..> eh : error
ts ..> eh : error
wf ..> eh : error
la ..> eh : error


eh --> send_error
send_error --> IncidentDB
}
@enduml